class BaseException(Exception):
    message: str

class InactiveEntityUsageError(BaseException):
    ...

class InvalidTitleError(BaseException):
    ...

class InvalidNumberError(BaseException):
    ...

class InvalidWorkingTimeError(BaseException):
    ...

class InvalidDescriptionError(BaseException):
    ...

class InvalidNameError(BaseException):
    ...

class InvalidPasswordError(BaseException):
    ...

class InvalidBookingTimeError(BaseException):
    ...

class BookingConfirmError(BaseException):
    ...

class BookingCancelError(BaseException):
    ...

class WorkplaceAlreadyExistError(BaseException):
    ...

class CommandHandlersNotFoundError(BaseException):
    ...

class QueryHandlerNotFoundError(BaseException):
    ...