class BaseException(Exception):
    message: str

class InactiveEntityUsageError(BaseException):
    ...

class InvalidSpotTitleError(BaseException):
    ...

class InvalidSpotNumberError(BaseException):
    ...

class InvalidWorkingTimeError(BaseException):
    ...

class InvalidDescriptionError(BaseException):
    ...

class InvalidNameError(BaseException):
    ...

class InvalidPasswordError(BaseException):
    ...

class InvalidBookingTimeError(BaseException):
    ...

class BookingConfirmError(BaseException):
    ...

class BookingCancelError(BaseException):
    ...
