"""empty message

Revision ID: 5a57cc2d517a
Revises: cff9f572be7f
Create Date: 2026-07-23 19:43:09.452611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a57cc2d517a'
down_revision: Union[str, Sequence[str], None] = 'cff9f572be7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('city', sa.String(length=50), nullable=False))
    op.add_column('workspaces', sa.Column('street', sa.String(length=200), nullable=False))
    op.add_column('workspaces', sa.Column('owner_id', sa.String(), nullable=False))
    op.create_foreign_key(None, 'workspaces', 'users', ['owner_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workspaces', type_='foreignkey')
    op.drop_column('workspaces', 'owner_id')
    op.drop_column('workspaces', 'street')
    op.drop_column('workspaces', 'city')
    # ### end Alembic commands ###
