"""replace DateTime columns to Time

Revision ID: 8e3d3cc4d4de
Revises: 39c431614969
Create Date: 2026-07-27 19:52:43.964044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8e3d3cc4d4de'
down_revision: Union[str, Sequence[str], None] = '39c431614969'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('booking', 'start_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.Time(timezone=True),
               existing_nullable=False)
    op.alter_column('booking', 'end_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.Time(timezone=True),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('booking', 'end_time',
               existing_type=sa.Time(timezone=True),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('booking', 'start_time',
               existing_type=sa.Time(timezone=True),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    # ### end Alembic commands ###
